-- Retire the legacy `daily-digest-nathan` cron job.
--
-- Audit 2026-04-27 (see docs/SEND_DAILY_DIGEST_AUDIT.md):
--   `daily-digest-nathan`  fires 0 12 * * *  → public.send_daily_digest()
--   `morning-sweep-daily`  fires 0 12 * * *  → Edge Function morning-sweep
--
-- Both at the exact same minute. The Edge Function is the canonical
-- daily 8am EDT digest going forward (richer Claude-written briefing,
-- per-deal AI summaries, per-deal overnight signals, pending-draft
-- review prompts).
--
-- Note: direct UPDATE on cron.job is permission-locked in Supabase
-- (ERROR 42501). The supported API is cron.unschedule(), which is
-- SECURITY DEFINER and bypasses the row-level lock. This removes the
-- job entry entirely.
--
-- public.send_daily_digest() is left in place. Its CREATE migration
-- isn't in git (created via SQL editor), so dropping it loses the
-- implementation. Leave it parked; can drop in a follow-up after a
-- stability window.
--
-- Reversal (only if needed):
--   select cron.schedule('daily-digest-nathan', '0 12 * * *',
--                         'SELECT public.send_daily_digest();');

select cron.unschedule('daily-digest-nathan');
